### ISSUE TITLE
Implement level of load tracking

### ISSUE THREAD

**Issue by mosc5** [rl-institut/fleema#84]
Level of load is a factor from 0-1. Max level of load depends on vehicle type (set when calculating demand table).

- [x] Level of load in schedule?
- [x] check level of load when getting demand (track in drive event?)
- [x] check if interpolation works
- [x] testing
